<?xml version="1.0"?>
<package format="2"><name>pod_sim</name><version>0.1.0</version><description>Payload, gimbal and target simulation boundary.</description><maintainer email="maintainers@example.com">Pod Software Team</maintainer><license>BSD-3-Clause</license><buildtool_depend>catkin</buildtool_depend><depend>diagnostic_msgs</depend><depend>geometry_msgs</depend><depend>roscpp</depend><depend>sensor_msgs</depend><depend>tracker</depend><depend>pod_msgs</depend></package>
