cmake_minimum_required(VERSION 3.0.2)
project(pod_mission_manager)
find_package(catkin REQUIRED COMPONENTS actionlib diagnostic_updater diagnostic_msgs follower roscpp std_srvs pod_msgs)
catkin_package(CATKIN_DEPENDS actionlib diagnostic_updater diagnostic_msgs follower roscpp std_srvs pod_msgs)
include_directories(${catkin_INCLUDE_DIRS})
add_executable(pod_mission_manager_node src/pod_mission_manager_node.cpp)
add_dependencies(pod_mission_manager_node ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})
target_compile_features(pod_mission_manager_node PRIVATE cxx_std_14)
target_link_libraries(pod_mission_manager_node ${catkin_LIBRARIES})
install(TARGETS pod_mission_manager_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config/ launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} OPTIONAL)
if(CATKIN_ENABLE_TESTING)
  find_package(rostest REQUIRED)
  add_rostest(test/mission_follow_lifecycle.test)
endif()
