cmake_minimum_required(VERSION 3.0.2)
project(pod_command_arbiter)
find_package(catkin REQUIRED COMPONENTS actionlib diagnostic_msgs roscpp std_srvs pod_msgs)
catkin_package(CATKIN_DEPENDS actionlib diagnostic_msgs roscpp std_srvs pod_msgs)
include_directories(${catkin_INCLUDE_DIRS})
add_executable(pod_command_arbiter_node src/pod_command_arbiter_node.cpp)
add_dependencies(pod_command_arbiter_node ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})
target_compile_features(pod_command_arbiter_node PRIVATE cxx_std_14)
target_link_libraries(pod_command_arbiter_node ${catkin_LIBRARIES})
install(TARGETS pod_command_arbiter_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config/ launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} OPTIONAL)

if(CATKIN_ENABLE_TESTING)
  find_package(catkin REQUIRED COMPONENTS rostest rospy)
  add_rostest(test/command_arbiter.test)
endif()
