cmake_minimum_required(VERSION 3.0.2)
project(pod_replay)
find_package(catkin REQUIRED COMPONENTS diagnostic_msgs rosbag roscpp tracker pod_msgs)
catkin_package(CATKIN_DEPENDS diagnostic_msgs rosbag roscpp tracker pod_msgs)
include_directories(${catkin_INCLUDE_DIRS})
add_executable(pod_replay_node src/pod_replay_node.cpp)
add_dependencies(pod_replay_node ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})
target_compile_features(pod_replay_node PRIVATE cxx_std_14)
target_link_libraries(pod_replay_node ${catkin_LIBRARIES})
install(TARGETS pod_replay_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config/ launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} OPTIONAL)
