cmake_minimum_required(VERSION 3.0.2)
project(pod_uav_adapter)
find_package(catkin REQUIRED COMPONENTS diagnostic_updater diagnostic_msgs follower geometry_msgs mavros_msgs mrs_msgs nav_msgs roscpp sensor_msgs std_srvs tf xd_uav_controller xd_uav_state_estimators pod_msgs)
catkin_package(CATKIN_DEPENDS diagnostic_updater diagnostic_msgs follower geometry_msgs mavros_msgs mrs_msgs nav_msgs roscpp sensor_msgs std_srvs tf xd_uav_controller xd_uav_state_estimators pod_msgs)
include_directories(${catkin_INCLUDE_DIRS})
add_executable(pod_uav_adapter_node src/pod_uav_adapter_node.cpp)
add_dependencies(pod_uav_adapter_node ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})
target_compile_features(pod_uav_adapter_node PRIVATE cxx_std_14)
target_link_libraries(pod_uav_adapter_node ${catkin_LIBRARIES})
install(TARGETS pod_uav_adapter_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config/ launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} OPTIONAL)
if(CATKIN_ENABLE_TESTING)
  find_package(rostest REQUIRED)
  add_rostest(test/uav_execution.test)
endif()
