cmake_minimum_required(VERSION 3.0.2)
project(pod_camera_driver)
find_package(catkin REQUIRED COMPONENTS diagnostic_msgs image_transport roscpp sensor_msgs pod_msgs)
catkin_package(CATKIN_DEPENDS diagnostic_msgs image_transport roscpp sensor_msgs pod_msgs)
include_directories(${catkin_INCLUDE_DIRS})
add_executable(pod_camera_driver_node src/pod_camera_driver_node.cpp)
add_dependencies(pod_camera_driver_node ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})
target_compile_features(pod_camera_driver_node PRIVATE cxx_std_14)
target_link_libraries(pod_camera_driver_node ${catkin_LIBRARIES})
install(TARGETS pod_camera_driver_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY config/ launch/ DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION} OPTIONAL)
